[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_vertexai_search"]

[project]
name = "mcp-vertexai-search"
version = "0.1.0"
authors = [{ name = "ubie" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10.0"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Information Technology",
  "Intended Audience :: System Administrators",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Typing :: Typed",
]
description = "A dbt artifacts parser in python"
dependencies = [
  "click>=8.3.1",
  "google-cloud-aiplatform>=1.144.0",
  "google-cloud-discoveryengine>=0.18.0",
  "loguru>=0.7.3",
  "mcp[cli]>=1.26.0",
  "pydantic>=2.12.5",
  "pyyaml>=6.0.3",
  "uvicorn>=0.42.0",
  "vertexai>=1.43.0",
]

[project.optional-dependencies]
dev = [
  "autopep8>=2.3.2",
  "bandit>=1.9.4",
  "black>=26.3.1",
  "google-genai>=1.69.0",
  "isort>=8.0.1",
  "langgraph>=1.1.4",
  "pytest>=9.0.2",
  "ruff>=0.15.8",
]


[project.scripts]
mcp-vertexai-search = "mcp_vertexai_search.cli:cli"
